issue #195 and issue #183. also kill counter disabled for now
COMP2522/project-bombpers pull request #196
Opened 2023-03-31 23:37 UTC by bli129

Danger level now resets on end and Collection Player changed to private. Kill Counter commented out until we make decision

2023-04-01 01:31 UTC, OzanYRT reviewed
Please review further more.

2023-04-01 01:31 UTC, OzanYRT commented on src/main/java/org/bcit/comp2522/project/CollectionManager.java
> +  public static CollectionManager getInstance() {
Should this method be static? Please review

2023-04-01 01:31 UTC, OzanYRT commented on src/main/java/org/bcit/comp2522/project/Window.java
> +    public CollectionManager collectionManager;
I am not sure if we want to keep the variables public.

2023-04-01 19:41 UTC, breader1 requested changes
Some things need to be addressed before this can be added to main. See the review comments please.

2023-04-01 19:41 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/CollectionManager.java
> +  public Sprite getPlayerInstance(Window window) {
GetPlayerInstance is supposed to instantiate the player. With player being private, this just needs to be getPlayer() because it will return the player. If we want to use the Collection manager to instantiate the player, then we need to remove the player instantiation from Window, and have this.player = Player.getInstance(); in the collectionManager constructor.

2023-04-01 19:41 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/CollectionManager.java
> +  public static CollectionManager getInstance() {
Collection manager is a singleton, This MUST be static or there's no way to get an instance of a CollectionManager

2023-04-01 19:41 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +    public CollectionManager collectionManager;
Agreed. This should be private.

2023-04-01 19:41 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +    public Player player;
Player is a Sprite. So Sprite Player, not Player player

2023-04-01 19:41 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +        collectionManager.getSprites().add(collectionManager.getPlayerInstance(this));
See above comments on this. If this is what you want to do, the player should be instantiated in the collection manager constructor.

2023-04-01 21:43 UTC, bli129 commented on src/main/java/org/bcit/comp2522/project/CollectionManager.java
> +  public Sprite getPlayerInstance(Window window) {
getPlayerInstance requires an argument for window. if we're to instantiate it in the constructor, we'd have to do something like passing an argument in the getInstance() for CollectionManager. if we want the getInstance() funcs to stay as zero-args, we'd have to instantiate outside the constructor. how do you want to implement this?

2023-04-01 22:32 UTC, bli129 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +        collectionManager.getSprites().add(collectionManager.getPlayerInstance(this));
this is the same implementation we had before but reduced to one line. if we want to do it differently, we'll have rethink design a little.

2023-04-02 00:09 UTC, bli129 commented
addressed the changes

2023-04-02 00:20 UTC, breader1 requested changes

2023-04-02 00:20 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +    private static Window currWindow;
If you want to reference 'this' window. Use 'this'. Don't do whatever you're doing here please.

2023-04-02 00:20 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +    public static Window getWindow() {
Delete this method please.

2023-04-02 00:20 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +        currWindow = this;
you can just use 'this'

2023-04-02 01:03 UTC, bli129 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +        currWindow = this;
the constructor for the collection manager will need an argument to pass for the getPlayerInstance then. this will break your code for the db manager stuff since it uses CollectionManager.getInstance(). how do you want to implement this then?

2023-04-02 04:58 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/Window.java
> +        currWindow = this;
I don't think that's the case. Could you please show me what you're talking about?

2023-04-02 22:11 UTC, breader1 commented
I reviewed the code more in-depth. I'm not certain we want to implement this. Can we close this PR, please?

2023-04-03 22:58 UTC, closed without merging