Branch ozan#210
COMP2522/project-bombpers pull request #221
Opened 2023-04-06 22:52 UTC by OzanYRT

Corrected a lot of checkstyle errors.

2023-04-06 23:09 UTC, bli129 approved these changes
The names need work, but this looks good as an initial constant refactor

2023-04-07 05:19 UTC, breader1 requested changes
I'm going to close this PR. There are too many imports when the variables we're referencing are static variables. 

We can talk as a group about a better option tomorrow, but for now, these changes would make the code require more refactoring.

2023-04-07 05:19 UTC, breader1 commented on src/main/java/org/bcit/comp2522/project/CollectionManager.java
> +import static org.bcit.comp2522.project.ConstantManager.ZERO;
This variable is static and should be referenced by the class. We don't want a bunch of imports like this

Example: ConstantManager.ZERO.

2023-04-07 05:20 UTC, breader1 commented
Too many imports on static class variables. We'll figure out a better strategy as a group sometimes on Friday.

2023-04-07 05:20 UTC, closed without merging