Checkstyle
COMP2522/project-bombpers pull request #229
Opened 2023-04-08 22:24 UTC by OzanYRT

Finished constant handling and did more checkstyle, remaining checkstyle are mostly javaDocs.

2023-04-08 22:28 UTC, bli129 approved these changes
looks good to mee

2023-04-09 00:16 UTC, bli129 commented on src/main/java/org/bcit/comp2522/project/ConstantManager.java
> +  public static final int ENEMY_SPAWNER_UI = 200;
very cool

2023-04-09 00:20 UTC, breader1 requested changes
@author tags are class level please.

There was a private variable changed to public, please change back.

2023-04-09 00:23 UTC, breader1 approved these changes
cool thanks :)

2023-04-09 00:23 UTC, merged